### ISSUE TITLE
"Profile" edit - cannot edit the Courses section

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#6] opened 2015-02-22 20:11 UTC

**Comment by derrick773** [comment] 2015-02-22 20:14
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by derrick773** [comment] 2015-02-22 20:32
![image](https://cloud.githubusercontent.com/assets/11150146/6320321/fad90222-baa7-11e4-9c94-1c5cdd13c3fa.png)

**Comment by yutarochan** [comment] 2015-02-22 22:09
Possible duplicate of:
https://github.com/WeStudee/WeStudee/issues/4
https://github.com/WeStudee/WeStudee/issues/7

**Comment by yutarochan** [comment] 2015-03-01 09:51
Resolved - Issue appears to be due to missing database row of corresponding user. Issue should be addressed when user initially creates an account with WeStudee.

**Closed as completed by yutarochan** 2015-03-01 09:51 UTC
Labels: bug, duplicate, functionality

**Comment by alexkamote** [comment] 2015-03-15 18:42
Chrome, Mac OS10.10.1. 

When I click edit courses it sends me to this page with no option to add courses. 

![edit westudee courses page](https://cloud.githubusercontent.com/assets/11151664/6657400/247e1cc8-cb08-11e4-957d-a3d90ccce24d.jpg)

**Comment by yutarochan** [comment] 2015-03-15 18:45
Resolved: Due to email restrictions lifted (email must match school address), course will not register properly. Manually added your account to the corresponding school database.
