### ISSUE TITLE
"Messages" / "In-app chat" does not work

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#12] opened 2015-02-22 20:25 UTC
Cannot open messages module

![image](https://cloud.githubusercontent.com/assets/11150146/6320253/f9403c2e-baa6-11e4-9b2f-eeb212612c47.png)

**Comment by derrick773** [comment] 2015-02-22 20:36
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by yutarochan** [comment] 2015-02-22 22:11
Possible duplicate of: https://github.com/WeStudee/WeStudee/issues/5

**Comment by yutarochan** [comment] 2015-02-22 23:33
Not implemented fully as of 2/22/15 18:33.

**Closed as completed** 2015-04-10 03:41 UTC
Labels: bug, duplicate, functionality
