### ISSUE TITLE
"Profile" edit - cannot edit the Availability section

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#7] opened 2015-02-22 20:12 UTC

**Comment by derrick773** [comment] 2015-02-22 20:13
Using Google Chrome v40.0.2214.115 m on Windows 7

**Comment by derrick773** [comment] 2015-02-22 20:25
![image](https://cloud.githubusercontent.com/assets/11150146/6320261/1266f792-baa7-11e4-9fd4-3186f1a01c91.png)

**Comment by yutarochan** [comment] 2015-02-22 22:09
Possible duplicate of:
https://github.com/WeStudee/WeStudee/issues/4
https://github.com/WeStudee/WeStudee/issues/7

**Comment by yutarochan** [comment] 2015-03-01 09:51
Resolved - Issue appears to be due to missing database row of corresponding user. Issue should be addressed when user initially creates an account with WeStudee.

**Closed as completed by yutarochan** 2015-03-01 09:51 UTC
Labels: bug, duplicate, functionality
